### ISSUE TITLE
trace file format

### ISSUE THREAD

**Issue by aymeric75** [AI-Planning/macq#209]
Hello,

I have a file trace where each line is alternatively a state (a 50 bits vector) then an action (an integer) etc, like so:

```
0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
0
0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
1
```

Is there an easy way to use (or convert) this file with Macq ?

Regards

**Comment by haz** [comment]
So there currently isn't a full support for this format, but it should be a great example of how to use the library (small wrapper should do the trick). I can whip something up for you.

Can you elaborate on what else you might have? Name for the fluents / actions, for example?

**Comment by aymeric75** [comment]
Thanks Christian

Names of the actions: a0, a1 ... up to a21 

Names of the fluents: z0, z1 ... up to z49

The actions are actually grounded actions (with grounded effects and preconditions), for instance, here, since I am working on Tower of Hanoi images, a0 would be move(d1, d2)

The fluents are only propositional variables, because I work with the latent values of a discrete VAE (from Latplan)

Regards

**Comment by haz** [comment]
Ah, good ol latplan...

So what you're after is pretty much already there. Give this script a try:

```python

from macq.generate.csv import load as load_traces_from_csv

data = """

plan_id,action,z0,z1,z2
1,a0,1,0,1
1,a1,0,1,0

""".strip()

with open("test.csv", "w") as f:
    f.write(data)

td = load_traces_from_csv("test.csv", "action", "plan_id")
td.print()
```

The `plan_id` lets you have different sequences of actions/states (i.e., multiple traces). If you have just one, then feel free to just use the same index for all the rows.

**Comment by haz** [comment]
Did this work for you, @aymeric75 ?

**Comment by haz** [comment]
Marking closed, as I think this is readily handled with the code snippet above

**Comment by aymeric75** [comment]
> Marking closed, as I think this is readily handled with the code snippet above

sorry for late reply, thanks for the code

I am looking into the library but I cannot find an easy way to generate a PDDL from the traces (ie from TraceList object)

Regards

**Comment by haz** [comment]
What do you mean generate PDDL? Do the action extraction and dump that to PDDL? If so, what type of trace data and extraction technique are you looking at? If it's fully observable and non-noisy, then chances are you want to use Observer. This is a good start to it: https://ai-planning.github.io/macq/macq/extract.html#observer

**Comment by aymeric75** [comment]
> What do you mean generate PDDL? Do the action extraction and dump that to PDDL? If so, what type of trace data and extraction technique are you looking at? If it's fully observable and non-noisy, then chances are you want to use Observer. This is a good start to it: https://ai-planning.github.io/macq/macq/extract.html#observer

Traces I have (see  my first comment) have noisy states, actions are the ground truth.

**Comment by haz** [comment]
It's a finicky method (haven't ever been able to get it to work well), but AMDN is the technique you're looking for. Here's a recipe that runs it on a problem file from the database:

```python
from macq.trace.disordered_parallel_actions_observation_lists import (
    default_theta_vec,
    num_parameters_feature,
    objects_shared_feature,
)

from macq.extract import Extract, modes
from macq.observation import NoisyPartialDisorderedParallelObservation
from macq.trace import DisorderedParallelActionsObservationLists
from macq import generate

traces = generate.pddl.VanillaSampling(problem_id = 4400, plan_len = 20, num_traces = 5, observe_pres_effs = True).traces

# traces.print(wrap="y")

features = [objects_shared_feature, num_parameters_feature]
learned_theta = default_theta_vec(2)
observations = traces.tokenize(
    Token=NoisyPartialDisorderedParallelObservation,
    ObsLists=DisorderedParallelActionsObservationLists,
    features=features,
    learned_theta=learned_theta,
    percent_missing=0,
    percent_noisy=0.2,
    replace=True,
)
model = Extract(observations, modes.AMDN, debug=False, occ_threshold=2)
assert model

model_blocks_dom = "test/d-compiled.pddl"
model_blocks_prob = "test/p-compiled.pddl"
model.to_pddl(
    "model_blocks_dom", "model_blocks_prob", model_blocks_dom, model_blocks_prob
)
```

**Comment by aymeric75** [comment]
Thanks a lot, I am almost there...

Executing this code:
```
from macq.trace.disordered_parallel_actions_observation_lists import (
    default_theta_vec,
    num_parameters_feature,
    objects_shared_feature,
)

from macq.extract import Extract, modes
from macq.observation import NoisyPartialDisorderedParallelObservation
from macq.trace import DisorderedParallelActionsObservationLists
from macq import generate
from macq.generate.csv import load as load_traces_from_csv

traces = load_traces_from_csv("merged_traces.csv", "action_id", "trace_id")

features = [objects_shared_feature, num_parameters_feature]
learned_theta = default_theta_vec(2)
observations = traces.tokenize(
    Token=NoisyPartialDisorderedParallelObservation,
    ObsLists=DisorderedParallelActionsObservationLists,
    features=features,
    learned_theta=learned_theta,
    percent_missing=0,
    percent_noisy=0.2,
    replace=True,
)
```

Where _merged_traces.csv_ is like:
```

trace_id,action_id,state_0,state_1,state_2,state_3,state_4,state_5,state_6,state_7,state_8,state_9,state_10,state_11,state_12,state_13,state_14,state_15,state_16,state_17,state_18,state_19,state_20,state_21,state_22,state_23,state_24,state_25,state_26,state_27,state_28,state_29,state_30,state_31,state_32,state_33,state_34,state_35,state_36,state_37,state_38,state_39,state_40,state_41,state_42,state_43,state_44,state_45,state_46,state_47,state_48,state_49
1,a0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,a1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,a2,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,a3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,0,1,1,0,1,0,0
1,a4,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,a5,0,0,0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0
```

I get:
```

Traceback (most recent call last):
  File "test2.py", line 19, in <module>
    observations = traces.tokenize(
  File "/workspace/macq/macq/trace/trace_list.py", line 135, in tokenize
    return ObsLists(self, Token, **kwargs)
  File "/workspace/macq/macq/trace/disordered_parallel_actions_observation_lists.py", line 176, in __init__
    self.tokenize(traces, Token, **kwargs)
  File "/workspace/macq/macq/trace/disordered_parallel_actions_observation_lists.py", line 298, in tokenize
    [p for p in a.precond]
```

Also, I dont know a priori the _percent_noisy_ value (I only have access to noisy states without info about the level of noise), will it still work ?

**Comment by haz** [comment]
Hrmz...it seems as though the tokenization is expecting the trace generation to come with the full action theory included: https://github.com/AI-Planning/macq/blob/main/macq/trace/disordered_parallel_actions_observation_lists.py#L98

This is needed because it de-orders actions based on the preconditions/effects. If this is coming from latplan style stuff, you won't have an action theory to go with.

Banged my head against all the moving parts here, and it's slowly coming back to me why we had to design it this way. AMDN assumes that actions are in unordered blocks of actions, and uses that assumption in processing things. In particular, even if I _could_ advise you on how to work around that (very method-specific) tokenization to have blocks of 1 action, AMDN would assume that every neighbouring pair of actions are set that way because of some conflicting effect/precondition pair. That's decidedly _not_ what you want.

So I think we're in a situation where AMDN is the only approach re-implemented that handles noisy states, but it comes with assumptions that don't make sense for your setting. It also means we really should try to get something implemented that's a simpler version of AMDN and targets directly the noisy state setting :P.

Sorry about the run-around!

**Comment by aymeric75** [comment]
I see, in parallel I am trying to use other existing methods for dealing with noisy states, like this [](https://ojs.aaai.org/index.php/ICAPS/article/view/31493) or this [](https://ieeexplore.ieee.org/document/9643159), I don't know how similar they are to AMDN though

Thanks anyway !

**Comment by haz** [comment]
Ya, if only the first paper authors used MACQ to implement their technique ;). Sorry we don't have better coverage on that space, yet!

**Comment by aymeric75** [comment]
yep, actually [this ](https://ieeexplore.ieee.org/document/9643159)one adviced me to try MACQ because its implem is not totally working with my settings

**Comment by haz** [comment]
Ah, I see. Well fingers crossed researchers start building on top of MACQ so we don't need to keep porting!
